spring:
  security:
    user:
      name: user
      password: 1111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show-sql: true
      format_sql: true
      use_sql_comments: true
      #  security:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/village
    username: admin
    password: password

